version: 2.1

jobs:
  test:
    parameters:
      go-version:
        type: string
    docker:
      - image: hossam1522/modatrack
    steps:
      - checkout
      - run:
          name: Actualizar versión de Go en go.mod
          command: |
            go mod edit -go parameters.go-version
      - run:
          name: Ejecutar tests
          command: task test

workflows:
  version: 2
  test-workflow:
    jobs:
      - test:
          matrix:
            parameters:
              go-version: ["1.11", "1.22.10", "1.23.4"]

