version: 2.1

jobs:
  test:
    machine:
      - image: cimg/go:1.23.3
    steps:
      - checkout
      - run:
          name: Pasar los tests con la imagen hossam1522/modatrack
          command: |
            docker run -u 1001 -t -v "$(pwd):/app/test" hossam1522/modatrack

workflows:
  version: 2
  test-workflow:
    jobs:
      - test
