version: 2.1

jobs:
  test:
    docker:
      - image: cimg/go:1.23.3
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Pull and run tests with hossam1522/modatrack image
          command: |
            docker pull hossam1522/modatrack
            docker run --rm hossam1522/modatrack task test

workflows:
  version: 2
  test-workflow:
    jobs:
      - test
