version: 2.1

jobs:
  test:
    docker:
      - image: hossam1522/modatrack
    steps:
      - checkout
      - run:
          name: Ejecutar tests
          command: task test

workflows:
  version: 2
  test-workflow:
    jobs:
      - test
