version: '2.1'
orbs:
  go: circleci/go@2.2.0
jobs:
  test:
    executor:
      name: go/default
      tag: 1.23.3
    steps:
      - checkout
      - run: 
          name: Pasar los tests con la imagen hossam1522/modatrack
          command: |
            docker run -u 1001 -t -v "$(pwd):/app/test" hossam1522/modatrack
workflows:
  main:
    jobs:
      - test
