version: 2.1

jobs:
  test:
    machine:
      image: ubuntu-2204:current
    steps:
      - checkout
      - run:
          name: Pasar los tests con la imagen hossam1522/modatrack
          command: |
            docker run -u 1001 -t -v "$(pwd):/app/test" hossam1522/modatrack

workflows:
  main:
    jobs:
      - test
