version: 2.1

jobs:
  test:
    parameters:
      go-version:
        type: string
    docker:
      - image: hossam1522/modatrack
    steps:
      - run:
          name: Actualizar versión de Go en go.mod
          command: |
            go mod edit -go << parameters.go-version >>
      - run:
          name: Actualizar versión de Go
          command: |
            wget -q https://go.dev/dl/go<< parameters.go-version >>.linux-amd64.tar.gz
            mkdir -p $HOME/go_new
            tar -C $HOME/go_new -xzf go<< parameters.go-version >>.linux-amd64.tar.gz
            rm go<< parameters.go-version >>.linux-amd64.tar.gz
            echo 'export PATH=$HOME/go_new/go/bin:$PATH' >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Verificar versión de Go
          command: go version
      - run:
          name: Ejecutar tests
          command: task test

workflows:
  version: 2
  test-workflow:
    jobs:
      - test:
          matrix:
            parameters:
              go-version: ["1.11", "1.23.4"]

