steps:
  - label: "Actualizar y probar Go"
    plugins:
      - docker#v5.12.0:
          image: hossam1522/modatrack
          environment:
            - GO_VERSION
    command: |
      # Actualizar la versión de Go en go.mod
      go mod edit -go ${GO_VERSION}

      # Descargar e instalar la nueva versión de Go
      wget -q https://go.dev/dl/go${GO_VERSION}.linux-amd64.tar.gz
      mkdir -p $HOME/go_new
      tar -C $HOME/go_new -xzf go${GO_VERSION}.linux-amd64.tar.gz
      rm go${GO_VERSION}.linux-amd64.tar.gz
      
      # Actualizar el PATH
      echo 'export PATH=$HOME/go_new/go/bin:$PATH' >> $BASH_ENV
      source $BASH_ENV

      # Verificar la versión de Go
      go version

      # Ejecutar tests
      task test

matrix:
  build.go_version:
    - "1.11"
    - "1.23.4"
