name: test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.11', '1.22.10']
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v4
      -
        name: Change go.mod version
        run: sed -i 's/^go .*/go ${{ matrix.go-version }}/' go.mod
      -
        name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      -
        name: Install task
        uses: arduino/setup-task@v2
      -
        name: Run tests
        run: task test